# Generated by Django 4.2.7 on 2024-02-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='remarks',
            field=models.CharField(default='Task not started yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
